RecipeBox page! After all these years...
agile-dev-assignments/project-setup-team-ntobo-global pull request #266
Opened 2021-04-01 17:20 UTC by Dendrobyte

- Alright, sorting on the front-end is good
- Also uncomments from app.js and all that fun stuff
- Contains proper route handler
- Date liked currently not filled in as we don't have information for that to practice with quite yet
![image](https://user-images.githubusercontent.com/12663558/113330534-d6e1ee00-92ec-11eb-985b-8d2aab8c52dd.png)

This officially resolves #17

2021-04-01 19:50 UTC, amn493 commented
A couple of notes:
- The tag search isn't working (maybe look at BrowseRecipesPage.js for reference ?)
- There is no keyword search bar (there should be)

Also, should we use icons for the ascending/descending button instead of text? It seems a little verbose right now.

2021-04-02 04:11 UTC, amn493 requested changes
I figured out how to fix the toggle button (as we discussed), but the other 2 changes still need to be made.

2021-04-02 18:30 UTC, Dendrobyte commented
- Auto complete tags (and being added as chips) and search bar added
![image](https://user-images.githubusercontent.com/12663558/113443124-563ff200-93bf-11eb-94d6-fcb3ebf075c1.png)

2021-04-02 22:44 UTC, amn493 approved these changes

2021-04-02 22:45 UTC, merged