add back import axios to FollowButton.js
agile-dev-assignments/project-setup-team-ntobo-global pull request #415
Opened 2021-04-13 00:44 UTC by oliviaedell

import statement removed during merge
resolves #219

2021-04-13 01:05 UTC, amn493 requested changes
This is crashing when I try to run it

2021-04-13 02:43 UTC, oliviaedell commented
@amn493 works for me now let me know if it still crashed on your end

2021-04-14 20:05 UTC, Dendrobyte commented
Program no longer crashes. Unsure exactly the entire purpose of this pr, but things work so if this is just a fix then approval from me. ik the lack of import was crashing when i tested so

2021-04-14 20:08 UTC, Dendrobyte approved these changes

2021-04-14 20:08 UTC, amn493 approved these changes

2021-04-15 22:38 UTC, merged