Database POST /comment
agile-dev-assignments/project-setup-team-ntobo-global pull request #420
Opened 2021-04-14 15:32 UTC by anvitayella

resolves #361

2021-04-14 20:53 UTC, Dendrobyte requested changes
In `RecipePage.js`, when calling the `<CommentsSection ...>` component, recipeId should be `recipe._id` as a prop (no longer `recipe.id`).  (around line 215)

Haven't been able to test bc it looks like Mockaroo is returning a 500 error for the `/comments` GET request, but the above is the only thing I noticed in the code which would result an something undefined being passed into the route handler. The change to database info looks good on the though (i.e. the files edited in this pr)

2021-04-15 16:45 UTC, amn493 requested changes
I was able to test it, and `app.js` looks great, but like Mark said, in `RecipePage.js`, lines 214 and 215 should look like this:
```
userId={props.user._id}
recipeId={recipe._id}
```

2021-04-15 16:58 UTC, amn493 approved these changes

2021-04-15 22:26 UTC, Dendrobyte approved these changes

2021-04-15 22:36 UTC, merged