prevent user from viewing full recipes of blocked user
agile-dev-assignments/project-setup-team-ntobo-global pull request #443
Opened 2021-04-19 05:30 UTC by oliviaedell

resolves #223

2021-04-19 21:29 UTC, JonathanSussman1 approved these changes
does as says, looks good!

2021-04-19 21:39 UTC, amn493 requested changes
The useEffect dependency array shouldn't have been modified.

2021-04-20 08:17 UTC, oliviaedell commented
> The useEffect dependency array shouldn't have been modified. This will cause the recipe to be fetched 3 times. Looks good aside from that.



> The useEffect dependency array shouldn't have been modified. This will cause the recipe to be fetched 3 times. Looks good aside from that.

@amn493 fixed

2021-04-21 02:08 UTC, amn493 approved these changes

2021-04-21 03:43 UTC, merged